### PR TITLE
Update gitea version to 1.11.3

### PR DESCRIPTION
**Pull request by DO1JLR**
Update Gitea Version to [v1.11.2](https://github.com/go-gitea/gitea/releases/tag/v1.11.2)

I tested it at my debian buster installation and there it is working fine.

### CODE REVIEW

**Comment by DO1JLR** [comment]
ping @thomas-maurice :heart:

**Comment by DO1JLR** [comment]
ping @thomas-maurice 

gitea is now available with version [v1.11.4](https://github.com/go-gitea/gitea/releases/tag/v1.11.4)

**Comment by DO1JLR** [comment]
hi @thomas-maurice 
Are you okay?

**Comment by thomas-maurice** [comment]
Sorry I lagged a bit behind for the reviews, looks LGTM to me :)

**Comment by DO1JLR** [comment]
It would be very nice if you merged the pull request as well @thomas-maurice .

**Comment by thomas-maurice** [comment]
Done :)

**Comment by DO1JLR** [comment]
thanks :heart:

**Pull request merged**
