### PR TITLE
Update gitea to 1.12.0

### PR DESCRIPTION
**Pull request by DO1JLR**
New gitea release [1.12.0](https://github.com/go-gitea/gitea/releases/tag/v1.12.0-rc1) is available \o/

### CODE REVIEW

**Comment by DO1JLR** [comment]
looks like 1.12.0 is only a pre-release. Sorry.

**Comment by em0lar** [comment]
Now it's released \o/

**Comment by DO1JLR** [comment]
Hmm, somehow travis doesn't report success.
Looks like it worked, though: [travis-ci.org/...builds/699846722](https://travis-ci.org/github/thomas-maurice/ansible-role-gitea/builds/699846722)

@thomas-maurice would you like to take a look at this on occasion? Thanks :kissing_heart:

**Comment by thomas-maurice** [comment]
Nice ! I dont know why the CI does not kick in though, thats weird

**Comment by thomas-maurice** [comment]
https://travis-ci.org/github/thomas-maurice/ansible-role-gitea/builds/699846722

**Pull request merged**
