### PR TITLE
Add metrics endpoint config support

### PR DESCRIPTION
**Pull request by madddi**

### CODE REVIEW

**Comment by thomas-maurice** [comment]
Thanks @madddi ! I'll gladly merge that when the merge conflicts are gone :)

**Comment by madddi** [comment]
@thomas-maurice perfect, conflicts are resolved :slightly_smiling_face:

**Comment by thomas-maurice** [comment]
@madddi can you also fix the linting errors pretty please ? :p https://travis-ci.org/thomas-maurice/ansible-role-gitea/builds/630975613?utm_source=github_status&utm_medium=notification

**Comment by madddi** [comment]
Sorry for the delay, fixed!

**Comment by thomas-maurice** [comment]
thanks

**Pull request merged**
