### PR TITLE
add default "gitea_group: gitea"

### PR DESCRIPTION
**Pull request by DO1JLR**
this will add the variable ``gitea_group: gitea``.

it is the suggested step to solve https://github.com/thomas-maurice/ansible-role-gitea/issues/70

### CODE REVIEW

**Review by thomas-maurice — DISMISSED** [review]
LGTM !

**Comment by thomas-maurice** [comment]
@DO1JLR can you fix the conflict and I happily merge this !

**Comment by DO1JLR** [comment]
@thomas-maurice done

**Comment by DO1JLR** [comment]
I also found out that the value of the variables ``gitea_lfs_jwt_secret`` and ``gitea_oauth2_jwt_secret`` should be exactly 43 characters long. Otherwise gitea overwrites this automagically and the config file is no longer idempotent.

**Comment by thomas-maurice** [comment]
Perfect

**Review by thomas-maurice — APPROVED** [review]

**Comment by thomas-maurice** [comment]
Still conflicts @DO1JLR :(

**Comment by DO1JLR** [comment]
> Still conflicts @DO1JLR :(
Are you sure? 

The github UI tells me all is ready for merging:
grafik

And my command line is telling me the same:
```
git merge origin/master fork/group
Bereits aktuell.
```

**Comment by thomas-maurice** [comment]
My bad I can squash and merge, thanks !

**Pull request merged**
