### PR TITLE
fix logging path

### PR DESCRIPTION
**Pull request by genofire**

### CODE REVIEW

**Review by DO1JLR — APPROVED** [review]

**Comment by thomas-maurice** [comment]
@DO1JLR what do you think, changing paths like that (like in #62) is likely to break existing installs isnt it ?

**Comment by genofire** [comment]
I do not know what you mean with #62 ....

This PR fix the inconsistense between:
https://github.com/thomas-maurice/ansible-role-gitea/blob/667c375a9de53f74dd079f12517c3df109485c82/templates/gitea.ini.j2#L178
and 
https://github.com/thomas-maurice/ansible-role-gitea/blob/667c375a9de53f74dd079f12517c3df109485c82/tasks/main.yml#L41


I believe the ansible creating path has no effect to the gitea installation ... gitea creats `/log` like in the ini file descripted at his own.

**Comment by thomas-maurice** [comment]
oooooooh fuck

My bad, I did not review that thoroughly enough, indeed you are right @genofire, sorry about that ! This can indeed be merged.

Thank you for doing that :)

**Review by thomas-maurice — APPROVED** [review]
Thanks :)

**Pull request merged**
