### PR TITLE
Upgrade/ansible version 2.10

### PR DESCRIPTION
**Pull request by TheRojam**
I refactored/upgraded the code for usage w/ ansible 2.10 and espescially I checked/improved the code regarding the new naming conventions. (collections)
(hopefully it now works w/ the travis-ci)

### CODE REVIEW

**Comment by thomas-maurice** [comment]
@TheRojam Thanks for doing this ! I will happily merge it after a rebase !

**Review by thomas-maurice — APPROVED** [review]

**Comment by thomas-maurice** [comment]
@TheRojam can you please rebase ? <3

**Comment by TheRojam** [comment]
> @TheRojam can you please rebase ? <3

i hopefully rebased this correctly, now... o.O

**Review by thomas-maurice — APPROVED** [review]
Thank you so much !

**Pull request merged**
