### PR TITLE
modify backup on upgrade

### LINKED ISSUE #80: gitea builtin update: permission denied
I just noticed that the backup can't work like this. The folder ``/var/backups/`` belongs to the user root on my system (debian 10).

My suggestion would be here once to design the backup as opt-in. and then also the backup path on the the one hand to design as variable, on the other hand with access authorization for the gitea user.

https://github.com/thomas-maurice/ansible-role-gitea/blob/56375819a72573c7fcdbc8e62ed0b674e6b7892b/tasks/install.yml#L30-L37

```
cmd/dump.go:171:fatal() [F] Unable to open gitea-dump-1613185611.zip: open gitea-dump-1613185611.zip: permission denied
```

### PR DESCRIPTION
**Pull request by DO1JLR**
+ make backup on upgrade optional (opt-in)
+ create backup path as variable
+ make sure the backup path has the right permissions
+ backup variables in README.md

FIX #80

### CODE REVIEW

**Comment by thomas-maurice** [comment]
Ah yes nice !

@DO1JLR can you run molecule locally ? Travis fucked up my credits and they will be replenished next month *loud eyeroll noises* and tell me if it works

Otherwise i'm happy to merge !

**Comment by DO1JLR** [comment]
sorry, but i have not yet acquired any experience in testing with molecule. Among other things, this is because I have not yet dealt with docker enough so that I want to install it locally.

But I could give you a more or less similar test based on github actions....

https://github.com/marketplace/actions/check-ansible-debian-latest

**Comment by DO1JLR** [comment]
it would be very nice if you can merge this @thomas-maurice .

because currently i think the folder that should be used for the backups (`/var/backups/`) is not writable for the gitea user. So the role is no longer usable when gitea needs to be updated.

**Comment by wzzrd** [comment]
Related: please switch the become_method on the backup task (back) to sudo. For me, because I do not run ansible as root, `become: su` cannot work: as created by this role, the gitea user does not have a password,  and my ansible user is not listed in my pam configuration as pam_rootok. I would guess that holds the same for most users.

Long story short: `become_method: su` breaks this role for me.

I have removed the `become_method: su` and `become_flags: -s /bin/sh` lines from the task, and ran the molecule tests on ubunt1804 (your default), el8 and fedora33 (my platform of choice) and all work fine. Tricky thing is that molecole with podman / docker probably always runs as root, so that test might not be completely fair.

I have also run it on my gitea server with a non-root account, and outside of a message around `remote_tmp`, all works fine.

Any specific reason the `become_method` is `su` here?

**Comment by DO1JLR** [comment]
the reason why i set the become_user flags like this is because they were already like this and i just took this part over.
https://github.com/thomas-maurice/ansible-role-gitea/blob/8b71e3f137e75006a52de7dd6bbbf765bcf03dff/tasks/install.yml#L34-L37

I personally am still totally on the warpath with the become_user method. I also tried the ``become_method: sudo`` locally and that didn't work either. This is also a reason why I expect the backup part to be optional. And of course because as a clueless ansible user I don't expect a role called gitea to do any big backups but to only install stuff and roll out config.

i will change the variant to the sudo method right away.

any other requests like special flags on this @wzzrd?

**Comment by DO1JLR** [comment]
Hey @thomas-maurice 
It would be really nice if you could look at this again. because currently the master branch of the role does not work for updates from gitea in my opinion.

**Comment by wzzrd** [comment]
So I merged your PR into my personal fork and ran from that today, and I was able to skip backup and deploy gitea 1.13.4 through  my personal Ansible Tower machine on Fedora 33. I have not tested the become stuff because I like the ability to skip the backup much better. I run backups through another mechanism, I really do not need that to happen during upgrade :)

**Comment by DO1JLR** [comment]
ping @thomas-maurice :kissing_heart:

**Review by thomas-maurice — APPROVED** [review]

**Comment by thomas-maurice** [comment]
Thanks @DO1JLR !

**Pull request merged**
